version: "3.9"
# docker build -t papermerge-core-ocr:standard -f docker/standard/Dockerfile .
services:
  papermerge:
    image: papermerge-core-ocr:standard
    container_name: papermerge-core-ocr
    ports:
      - "8000:80" # Expose the application on port 8000
    environment:
      PAPERMERGE__DATABASE__URL: "postgresql://testuser:testpass@127.0.0.1:5434/testdb"
      PAPERMERGE__REDIS__URL: "redis://127.0.0.1:6379/0"
      PAPERMERGE__MAIN__MEDIA_ROOT: "/app/media"
      PAPERMERGE__MAIN__LOGGING_CFG: "/etc/papermerge/logging.yaml"
      CELERY_BROKER_URL: "redis://127.0.0.1:6379/0"
      CELERY_RESULT_BACKEND: "redis://127.0.0.1:6379/0"
      PAPERMERGE__AUTH__EMAIL: "cubecore27@gmail.com"
      PAPERMERGE__AUTH__PASSWORD: "123"
      PAPERMERGE__AUTH__USERNAME: "marco"
      PAPERMERGE__CORE__BASE_URL: "http://localhost:8000"
      PAPERMERGE__MAIN__API_PREFIX: "/api"
      PAPERMERGE__OCR__DEFAULT_LANG_CODE: "fil"
      PAPERMERGE__OCR__LANG_CODES: "eng,deu,spa,fil"
      PAPERMERGE__SECURITY__SECRET_KEY: "12345"
      OCR_WORKER_ARGS: -Q ocr -E --loglevel=DEBUG
    volumes:
      - ~/var/pmgdata:/app/media # Mount the storage directory