version: "3.9"
# docker build -t papermerge-core-ocr:standard -f docker/standard/Dockerfile .
# dos2unix docker/standard/entrypoint.sh
# docker-compose -f docker-compose.full_local.yml up -d
# docker-compose -f docker-compose.full_local.yml down
services:
  solr:
    image: solr:9.7
    container_name: papermerge-solr
    restart: unless-stopped
    ports:
      - "8983:8983"
    command:
      - solr-precreate
      - papermerge
    volumes:
      - solr_data:/var/solr

  redis:
    image: redis:7
    container_name: pmg_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  db:
    image: postgres:16.1
    container_name: pm-db
    restart: unless-stopped
    ports:
      - "5433:5432"  # Avoid conflict with native Postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-your_db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_db_password}
      POSTGRES_DB: ${POSTGRES_DB:-your_db_name}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  db_ephemeral:
    image: postgres:16.1
    container_name: pm-db-ephemeral
    restart: unless-stopped
    ports:
      - "5434:5432"   # different port to avoid conflict
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER:-testuser}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD:-testpass}
      POSTGRES_DB: ${TEST_POSTGRES_DB:-testdb}
    tmpfs:
      - /var/lib/postgresql/data  # ephemeral storage
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  ocrworker:
    build:
      context: .
      dockerfile: docker/standard/Dockerfile
    image: custom-ocrworker:tagalog
    container_name: ocr-worker
    restart: unless-stopped
    command: ["worker"]
    environment:
      PAPERMERGE__DATABASE__URL: ${PAPERMERGE__DATABASE__URL:-postgresql://user:pass@db:5432/dbname}
      PAPERMERGE__REDIS__URL: ${PAPERMERGE__REDIS__URL:-redis://redis:6379/0}
      PAPERMERGE__MAIN__MEDIA_ROOT: ${PAPERMERGE__MAIN__MEDIA_ROOT:-/app/media}
      OCR_WORKER_ARGS: ${OCR_WORKER_ARGS:--Q ocr -E --loglevel=DEBUG}
      PAPERMERGE__MAIN__LOGGING_CFG: ${PAPERMERGE__MAIN__LOGGING_CFG:-/etc/papermerge/logging.yaml}
    volumes:
      - ~/var/pmgdata:/app/media
    depends_on:
      - db
      - redis

  i3worker:
    image: papermerge/i3worker:0.3.1b1
    container_name: i3-worker
    restart: unless-stopped
    command: ["worker"]  # required by entrypoint.sh
    environment:
      PAPERMERGE__DATABASE__URL: ${PAPERMERGE__DATABASE__URL:-postgresql://user:pass@db:5432/dbname}
      PAPERMERGE__REDIS__URL: ${PAPERMERGE__REDIS__URL:-redis://redis:6379/0}
      PAPERMERGE__SEARCH__URL: ${PAPERMERGE__SEARCH__URL:-solr://solr:8983/papermerge}
      I3_WORKER_ARGS: ${I3_WORKER_ARGS:--Q i3 -E --loglevel=DEBUG}
      PAPERMERGE__MAIN__LOGGING_CFG: ${PAPERMERGE__MAIN__LOGGING_CFG:-/etc/papermerge/logging.yaml}
    depends_on:
      - db
      - redis
      - solr

  papermerge:
    image: papermerge-core-ocr:standard
    container_name: papermerge-core-app
    ports:
      - "8000:80"
    environment:
      PAPERMERGE__DATABASE__URL: ${PAPERMERGE__DATABASE__URL:-postgresql://user:pass@db:5432/dbname}
      PAPERMERGE__REDIS__URL: ${PAPERMERGE__REDIS__URL:-redis://redis:6379/0}
      PAPERMERGE__SEARCH__URL: ${PAPERMERGE__SEARCH__URL:-solr://solr:8983/papermerge}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://redis:6379/0}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
      PAPERMERGE__MAIN__MEDIA_ROOT: ${PAPERMERGE__MAIN__MEDIA_ROOT:-/app/media}
      PAPERMERGE__S3__BUCKET_NAME: ${PAPERMERGE__S3__BUCKET_NAME:-your_bucket}
      AWS_REGION_NAME: ${AWS_REGION_NAME:-your_region}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-your_access_key}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-your_secret_key}
      S3_WORKER_ARGS: ${S3_WORKER_ARGS:---loglevel=debug -Q s3 -c 2 -E}
      AWS_S3_ADDRESSING_STYLE: ${AWS_S3_ADDRESSING_STYLE:-path}
      PAPERMERGE__AUTH__USERNAME: ${PAPERMERGE__AUTH__USERNAME:-your_admin_user}
      PAPERMERGE__AUTH__EMAIL: ${PAPERMERGE__AUTH__EMAIL:-your_admin_email}
      PAPERMERGE__AUTH__PASSWORD: ${PAPERMERGE__AUTH__PASSWORD:-your_admin_password}
      PAPERMERGE__SECURITY__SECRET_KEY: ${PAPERMERGE__SECURITY__SECRET_KEY:-your_secret_key}
      PAPERMERGE__MAIN__API_PREFIX: ${PAPERMERGE__MAIN__API_PREFIX:-}
      PAPERMERGE__CORE__BASE_URL: ${PAPERMERGE__CORE__BASE_URL:-http://localhost:8000}
      PAPERMERGE__OCR__LANG_CODES: ${PAPERMERGE__OCR__LANG_CODES:-eng,deu,spa,fil}
      PAPERMERGE__EMAIL__SMTP_HOST: ${PAPERMERGE__EMAIL__SMTP_HOST:-smtp.example.com}
      PAPERMERGE__EMAIL__SMTP_PORT: ${PAPERMERGE__EMAIL__SMTP_PORT:-587}
      PAPERMERGE__EMAIL__SMTP_USERNAME: ${PAPERMERGE__EMAIL__SMTP_USERNAME:-your_email}
      PAPERMERGE__EMAIL__SMTP_PASSWORD: ${PAPERMERGE__EMAIL__SMTP_PASSWORD:-your_email_password}
      PAPERMERGE__EMAIL__SMTP_USE_TLS: ${PAPERMERGE__EMAIL__SMTP_USE_TLS:-false}
      PAPERMERGE__EMAIL__SMTP_START_TLS: ${PAPERMERGE__EMAIL__SMTP_START_TLS:-true}
      PAPERMERGE__EMAIL__FROM_ADDRESS: ${PAPERMERGE__EMAIL__FROM_ADDRESS:-noreply@example.com}
      PAPERMERGE__FRONTEND__URL: ${PAPERMERGE__FRONTEND__URL:-https://your-frontend-url}
    volumes:
      - ~/var/pmgdata:/app/media
    depends_on:
      - db
      - redis
      - solr

volumes:
  pgdata:
  solr_data: # Declare the solr_data volume here
