name: Build Dev Image

on:
  workflow_dispatch:
    inputs:
      VERSION:
        required: true
        description: Docker tag e.g. 3.0dev1, 3.0dev2
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}  # checkout current branch
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build ${{ inputs.VERSION }} Dev Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: papermerge/papermerge:${{ inputs.VERSION }}
          file: docker/dev/Dockerfile
          platforms: linux/amd64
